// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUj9g6bxmcF9GQM35ZnBxesPRFXdwJ0Q',
    appId: '1:755076027233:web:92d0f99bf6351ced6ceb20',
    messagingSenderId: '755076027233',
    projectId: 'music-player-app-d740a',
    authDomain: 'music-player-app-d740a.firebaseapp.com',
    storageBucket: 'music-player-app-d740a.appspot.com',
    measurementId: 'G-RG887XKY5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm2RDgMvyCMuJg3JC6hkCeDW1YCG2WPrk',
    appId: '1:755076027233:android:67d0aeb519394b8a6ceb20',
    messagingSenderId: '755076027233',
    projectId: 'music-player-app-d740a',
    storageBucket: 'music-player-app-d740a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CbpLi7AqipSIwlmqgr1UtOEg3bXO2c0',
    appId: '1:755076027233:ios:124334ff6dc97f6f6ceb20',
    messagingSenderId: '755076027233',
    projectId: 'music-player-app-d740a',
    storageBucket: 'music-player-app-d740a.appspot.com',
    iosClientId: '755076027233-oqk8agiqqi07g8fmgd57brnjt4cmel49.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4CbpLi7AqipSIwlmqgr1UtOEg3bXO2c0',
    appId: '1:755076027233:ios:0f211dc74c1d54d46ceb20',
    messagingSenderId: '755076027233',
    projectId: 'music-player-app-d740a',
    storageBucket: 'music-player-app-d740a.appspot.com',
    iosClientId: '755076027233-8foce21n3stp7v11raum4qo20b2cfgr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicPlayer.RunnerTests',
  );
}
